# Generated by Django 5.0.6 on 2024-05-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalens_app', '0002_dataset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='uploads/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalens_app.dataset')),
            ],
        ),
    ]
